In [5]:
!pip install langdetect

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 981 kB 30.6 MB/s 
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993242 sha256=3a0e613e016535ac7f5b4875f390e3fbec05d877d9193947ede08811a401bc01
  Stored in directory: /root/.cache/pip/wheels/c5/96/8a/f90c59ed25d75e50a8c10a1b1c2d4c402e4dacfa87f3aff36a
Successfully built langdetect


In [6]:
import tensorflow as tf
import subprocess
import os
import pandas as pd
import random
import shutil
import numpy as np
import json
import re
import pathlib

from langdetect import detect
from google.colab import drive, files #if use colab
from tensorflow.nn import relu, tanh, softmax
from tensorflow.keras import layers
from tensorflow.keras.models import Model
from tensorflow.lite.python import interpreter
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [7]:
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
git_dir = '/content/IOH-Chat-App'
git_url = 'https://github.com/bangkit-team/IOH-chat-app.git'

if not os.path.exists(git_dir):
  subprocess.call(['git', 'clone', git_url])

In [14]:
filedir = '/content/IOH-chat-app/MachineLearning/datasets/translation/result/eng-ind.csv'

In [15]:
df = pd.read_csv(filedir)
df

English  \
0                                                   Run!   
1                                                   Who?   
2                                                   Wow!   
3                                                  Help!   
4                                                  Jump!   
...                                                  ...   
15359  Limitation of this capability causes opportuni...   
15360  Subjective approach evaluates poverty based on...   
15361  Limited sufficiency and food quality , seen fr...   
15362  Around 20 percents people with the lowest inco...   
15363  Deficiency of calory intake , namely less than...   

                                               Indonesia  
0                                                  Lari!  
1                                                 Siapa?  
2                                                   Wow!  
3                                                Tolong!  
4                                                Lompat!  
...                                                  ...  
15359  Keterbatasan kemampuan ini menyebabkan tertutu...  
15360  Pendekatan subyektif menilai kemiskinan berdas...  
15361  terbatasnya kecukupan dan mutu pangan , diliha...  
15362  Sekitar 20 persen penduduk dengan tingkat pend...  
15363  Kekurangan asupan kalori , yaitu kurang dari 2...  

[15364 rows x 2 columns]

In [16]:
start_mark = '<start>'
end_mark = '<end>'

In [385]:
class TranslatorDataset:
  def __init__(self, dataframe):
    self.dataframe = dataframe
    self.input_tokenizer = None
    self.target_tokenizer = None
    self._load_data_from_file()

  def _load_data_from_file(self):
    df = self.dataframe

    input_lang = df.English.values
    target_lang = df.Indonesia.values

    return input_lang, target_lang

  def _normalize_and_preprocess(self, text, use_mark=False):
    if use_mark:
      text = text.strip()
      text = ' '.join([start_mark, text, end_mark])
    else:
      text = text.strip()

    return text

  def _tokenize(self, sentences, num_words, maxlen):
    punctuation = '!"#$%&()*+,-./:;=?@[\\]^_`{|}~\t\n'

    tokenizer = Tokenizer(num_words=num_words, filters=punctuation)
    tokenizer.fit_on_texts(sentences)

    sequences = tokenizer.texts_to_sequences(sentences)
    sequences = pad_sequences(
        sequences, maxlen=self.maxlen, padding='post', truncating='post')

    return sequences, tokenizer

  def _create_dataset(self):
    input_lang, target_lang = self._load_data_from_file()

    input_sentence = np.array(
        list(map(lambda x: self._normalize_and_preprocess(x, False), input_lang)))
    
    target_sentence = np.array(
        list(map(lambda y: self._normalize_and_preprocess(y, True), target_lang)))
    
    return input_sentence, target_sentence

  def _load_dataset(self, num_words):
    input_lang, target_lang = self._create_dataset()

    self.maxlen = 20
    self.buffer_size = len(input_lang)

    input_sequences, input_tokenizer = self._tokenize(
        input_lang, num_words, self.maxlen)
    
    target_sequences, target_tokenizer = self._tokenize(
        target_lang, num_words, self.maxlen,)

    return (input_sequences, input_tokenizer), (target_sequences, target_tokenizer)
  
  def get(self, num_words, batch_size):
    input, target = self._load_dataset(num_words)

    input_sequences, self.input_tokenizer = input
    target_sequences, self.target_tokenizer = target

    dataset = tf.data.Dataset.from_tensor_slices((input_sequences, target_sequences))
    dataset = dataset.shuffle(self.buffer_size).batch(batch_size, drop_remainder=True)
    dataset = dataset.cache().prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

    return self.input_tokenizer, self.target_tokenizer, dataset

In [386]:
num_words = 20000
batch_size = 64

In [387]:
translator_dataset = TranslatorDataset(df)

input_tokenizer, target_tokenizer, dataset = translator_dataset.get(num_words, batch_size)

In [388]:
input_batch, target_batch = next(iter(dataset))

In [389]:
input_batch.shape, target_batch.shape

(TensorShape([64, 20]), TensorShape([64, 20]))

In [390]:
input_vocab_size = len(input_tokenizer.index_word) + 1
target_vocab_size = len(target_tokenizer.index_word) + 1
input_maxlen = input_batch.shape[1]
target_maxlen = target_batch.shape[1]

input_maxlen, target_maxlen, input_vocab_size, target_vocab_size

(20, 20, 12035, 13498)

In [391]:
inp_wi = input_tokenizer.word_index

with open('inp_wi.json', 'w') as f:
  json.dump(inp_wi, f)

# files.download('inp_wi.json')

In [392]:
targ_iw = target_tokenizer.index_word

with open('targ_iw.json', 'w') as f:
  json.dump(targ_iw, f)

# files.download('targ_iw.json')

In [393]:
input_example = input_batch[-1]
input_example

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([1117,  912, 1830,  327,  110,  204,   75,   97, 2172,  131,  517,
        846,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)>

In [394]:
target_example = target_batch[-1]
target_example

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([   1,  237, 2123, 4879,  819,  432,  631,  105,  295,   85,  766,
       3806,    3,   83,  507,    2,    0,    0,    0,    0], dtype=int32)>

In [395]:
input_sentence = input_tokenizer.sequences_to_texts([input_example.numpy()])[0]
input_sentence

'village agricultural workers work all day but they receive very little payments'

In [396]:
target_sentence = target_tokenizer.sequences_to_texts([target_example.numpy()])[0]
target_sentence

'<start> para buruh tani desa bekerja sepanjang hari tetapi mereka menerima upah yang sangat sedikit <end>'

In [397]:
embed_dims = 512
units = 1024

In [398]:
class Encoder():
  def __init__(self, input_vocab_size, embedding_dims, units):
    self.units = units
    self.batch_size = batch_size
    self.input_vocab_size = input_vocab_size
    self.embedding_dims = embedding_dims

    self.embedding = layers.Embedding(self.input_vocab_size, self.embedding_dims)
    self.lstm_layer = layers.LSTM(self.units,
                                 return_sequences=True,
                                 return_state=True,
                                 recurrent_initializer='glorot_uniform')

  def call(self, inputs):
    embedding = self.embedding(inputs)
    encoder = self.lstm_layer(embedding)

    return encoder

In [399]:
class BahdanauAttention(layers.Layer):
  def __init__(self, units):
    super(BahdanauAttention, self).__init__()
    self.w1 = layers.Dense(units, use_bias=True) 
    self.w2 = layers.Dense(units, use_bias=True) 
    self.fd = layers.Dense(1)

  def call(self, query, values):
    query_with_time_axis = tf.expand_dims(query, 1)
    
    score = self.fd(tanh(
        self.w1(query_with_time_axis) + self.w2(values)))

    attention_weights = softmax(score, axis=1)

    context_vector = attention_weights * values
    context_vector = tf.reduce_sum(context_vector, axis=1)

    return context_vector, attention_weights

In [400]:
class Decoder:
  def __init__(self, output_vocab_size, embedding_dims, units):
    self.units = units
    self.output_vocab_size = output_vocab_size
    self.embedding_dims = embedding_dims

    self.embedding = layers.Embedding(self.output_vocab_size, self.embedding_dims)
    self.lstm_layer = layers.LSTM(self.units,
                                  return_sequences=True,
                                  return_state=True,
                                  recurrent_initializer='glorot_uniform')
    self.attention = BahdanauAttention(self.units)
    self.dense1 = layers.Dense(self.units, activation=tanh, use_bias=False)
    self.dropout = layers.Dropout(.5)
    self.dense2 = layers.TimeDistributed(layers.Dense(self.output_vocab_size))

  def call(self, inputs, en_outputs, state):
    embedding = self.embedding(inputs)
    dec_outputs, dec_h_state, dec_c_state = self.lstm_layer(
        embedding, initial_state=state)
    
    context_vector, attention_weights = self.attention(
        query=dec_outputs, values=en_outputs)
    
    context_and_rnn_output = tf.concat([context_vector, dec_outputs], axis=-1)

    attention_vector = self.dense1(context_and_rnn_output)
    outputs = self.dropout(attention_vector)
    outputs = self.dense2(outputs)

    return outputs, attention_weights

In [401]:
encoder = Encoder(input_vocab_size, embed_dims, units)

en_outputs, en_h_state, en_c_state = encoder.call(input_batch)

en_outputs.shape, en_h_state.shape, en_c_state.shape

(TensorShape([64, 20, 1024]), TensorShape([64, 1024]), TensorShape([64, 1024]))

In [402]:
decoder = Decoder(target_vocab_size, embed_dims, units)
dec_outputs, _= decoder.call(target_batch, en_outputs, [en_h_state, en_c_state])

dec_outputs.shape

ResourceExhaustedError: ignored

In [364]:
lr = 0.001
epochs = 30

optimizer = tf.keras.optimizers.Adam(
    learning_rate=lr, beta_1=0.9, beta_2=0.98, epsilon=1e-9)
loss = tf.keras.losses.SparseCategoricalCrossentropy(
       from_logits=True, reduction='none')

In [365]:
class TranslatorModel:
  def __init__(self, input_vocab_size, 
               target_vocab_size, 
               embed_dims, 
               units):
    self.input_vocab_size = input_vocab_size
    self.target_vocab_size = target_vocab_size
    self.embed_dims = embed_dims
    self.units = units

    self.encoder = Encoder(
        self.input_vocab_size, self.embed_dims, self.units)
    
    self.decoder = Decoder(
        self.target_vocab_size, self.embed_dims, self.units)
  
  def build_model(self):
    en_inputs = layers.Input(shape=(None,))

    en_output, en_h_state, en_c_state = self.encoder.call(en_inputs)

    dec_outputs, _ = self.decoder.call(
        en_inputs, en_output, [en_h_state, en_c_state])

    model = Model(inputs=[en_inputs], 
                  outputs=[dec_outputs])
    return model

In [366]:
translator_model = TranslatorModel(
    input_vocab_size,
    target_vocab_size,
    embed_dims,
    units,
)
model = translator_model.build_model()

model.compile(
    optimizer=optimizer,
    loss=loss,
    metrics=['accuracy']
)

In [367]:
checkpoint_path = 'checkpoint/cp.ckpt'
checkpoint_dir = os.path.dirname(checkpoint_path)

callback_early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='loss',
    patience=3, 
    verbose=1)

callback_checkpoint = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path, 
    monitor='loss', 
    verbose=1, 
    save_weights_only=True, 
    save_best_only=True)

callbacks = [callback_early_stopping,
             callback_checkpoint]

model.summary()

Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_6 (InputLayer)           [(None, None)]       0           []                               
                                                                                                  
 embedding_24 (Embedding)       (None, None, 512)    6161920     ['input_6[0][0]']                
                                                                                                  
 embedding_25 (Embedding)       (None, None, 512)    6910976     ['input_6[0][0]']                
                                                                                                  
 lstm_24 (LSTM)                 [(None, None, 1024)  6295552     ['embedding_24[0][0]']           
                                , (None, 1024),                                             

In [368]:
model.fit(dataset,
          epochs=epochs,
          callbacks=callbacks,
          verbose=1)

Epoch 1/30


ResourceExhaustedError: ignored

In [ ]:
saved_model_path = '/content/drive/MyDrive/Company Case Bangkit/TranslationModel/saved_model'
saved_model_dir = os.path.dirname(saved_model_path)

if os.path.exists(saved_model_dir):
  shutil.rmtree(saved_model_dir)
  
model.save(saved_model_path)

In [ ]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS
]
converter.experimental_new_converter = True
converter.allow_custom_ops = True

tflite_model = converter.convert()

tflite_model_file = pathlib.Path('translation.tflite')
tflite_model_file.write_bytes(tflite_model)

In [ ]:
interpreter = tf.lite.Interpreter('translation.tflite')
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

input_details, output_details

In [ ]:
class Translator(tf.Module):
  def __init__(self, model_path, inp_word_index, targ_index_word, maxlen):
    self.model_path = model_path
    self.inp_word_index = inp_word_index
    self.targ_index_word = targ_index_word
    self.maxlen = maxlen

    self._load_model()
    self._load_vocab()

  def _load_model(self):
    self.model = tf.keras.models.load_model(self.model_path, compile=True)
  
  def _load_vocab(self):
    inp_json = open(self.inp_word_index)
    self.inp_vocab = json.load(inp_json)
    inp_json.close()

    targ_json = open(self.targ_index_word)
    vocab = json.load(targ_json)
    self.targ_vocab = {int(k):v for k,v in vocab.items()}
    targ_json.close()

  def _normalize_and_preprocess(self, text):
    punctuation = '!"#$%&()*+,-./:;=?@[\\]^_`{|}~\t\n'
    
    text = text.lower().strip()
    text = ''.join((filter(lambda x: x not in punctuation, text)))

    return text

  def _texts_to_sequences(self, text):
    words = text.split(" ")
    sequences = list()

    for word in words:
      if word in self.inp_vocab.keys():
        token = self.inp_vocab[word]
        sequences.append(token)

    return sequences

  def _sequences_to_texts(self, sequences):
    words = list()

    for token in sequences:
      if token in self.targ_vocab.keys():
        word = self.targ_vocab[token]
        words.append(word)    

    return words 

  def lang_detector(self, sentence):
      return detect(sentence)

  def __call__(self, sentence):
    index_prediction = list()

    normalize_sentence = self._normalize_and_preprocess(sentence)
    sequences = self._texts_to_sequences(normalize_sentence)
    sequences = pad_sequences(
        [sequences], maxlen=self.maxlen, padding="post", truncating="post")

    predictions = self.model(sequences)

    for i in predictions[0]:
        index_prediction.append(np.argmax(i))

    marks = [start_mark, end_mark]
    result = self._sequences_to_texts(index_prediction)

    result = ' '.join([word for word in result if word not in marks])

    return result

In [ ]:
inp_vocab_path = '/content/inp_wi.json'
targ_vocab_path = '/content/targ_iw.json'

translator = Translator(
    saved_model_path,
    inp_vocab_path,
    targ_vocab_path,
    input_maxlen)

In [369]:
text_input = 'this is my home'
lang_detector = translator.lang_detector(text_input)

if lang_detector == 'en':
  translate = translator(text_input)
  print(translate)
else:
  print('Kata ini tidak berbahasa Inggris')

['<start>', 'ini', 'ayahku', 'saya']
ini ayahku saya
